version: '2.1'
services:

    Oposed-Api:
      image: oposed_api
      #ports:
      #  - "5000:5000"
      environment:
        #- ASPNETCORE_ENVIRONMENT=Development
        - LDAP_ADMIN_GROUP_DN=
        - LDAP_BASE_DN=
        - LDAP_BIND_DN=
        - LDAP_BIND_PASSWORD=
        - LDAP_FILTER_USER=
        - LDAP_SERVER_HOST=
        - LDAP_SERVER_PORT=389
        - SMTP_ENABLE_SSL=true
        - SMTP_MAIL_ADDRESS=
        - SMTP_MAIL_PASSWORD=
        - SMTP_SERVER_HOST=
        - SMTP_SERVER_PORT=465
      volumes:
        - db:/app/Database/
      restart: always
      networks:
        - oposed-network
        
    Oposed-Web:
      image: oposed_web
      ports:
        - "80:80"
      environment:
        #- ASPNETCORE_ENVIRONMENT=Development
        - URL_LOGO=/img/Oposed-Logo.png
        - URL_IMPRESSUM=
        - URL_API=http://Oposed-Api:5000
        - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
        #- LC_ALL=de_DE.UTF-8
        #- LANG=de_DE.UTF-8
      depends_on:
        - oposed_api
      restart: always
      networks:
        - oposed-network

volumes:
  db:

networks:
  oposed-network:
    driver: bridge